import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ProjectCard from "@/components/common/ProjectCard";
import jasonimg from "@/public/assets/img/me.jpg";
import fsPromises from "fs/promises";
import path from "path";

const inter = Inter({ subsets: ["latin"] });

// retrieves all of my previous work from work.json
export const getStaticProps = async () => {
  const filePath = path.join(process.cwd(), "json/work.json");
  const jsonData: any = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);

  return {
    props: objectData,
  };
};

type WorkProps = {
  work: any;
};

export default function Home({ work }: WorkProps) {
  return (
    <>
      <Head>
        <title>jasonzubiate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.hero_content}>
            <h1 className={styles.h1}>Jason Zubiate</h1>
            <h2 className={styles.catchline}>
              0 to 1 designer - of software, interfaces, and experiences
            </h2>
            <div className={styles.statuses}>
              <div className={styles.status}>
                <label className={styles.status_title}>Currenly</label>
                <label className={styles.status_body}>Preparing for gradute school in fall 2023</label>
              </div>
              <div className={styles.vl}></div>
              <div className={styles.status}>
                <label className={styles.status_title}>Thinking About</label>
                <label className={styles.status_body}>
                  Latest design trends, AI potential, new techniques in dance
                  music production
                </label>
              </div>
              <div className={styles.vl}></div>
              <div className={styles.status}>
                <label className={styles.status_title}>Previously</label>
                <label className={styles.status_body}>
                  UX Lead @{" "}
                  <span className={styles.bold}>
                    <a className="link" href="https://www.nutripair.co/">
                      Nutripair
                    </a>
                  </span>
                </label>
              </div>
            </div>
          </div>
          <div className={styles.hero_image}>
            <Image
              className={styles.img}
              src={jasonimg}
              alt={"Jason Zubiate"}
              quality={100}
            />
          </div>
        </div>
        <div className={styles.work}>
          <h2 className={styles.h2}>My Work</h2>
          <div className={styles.projects}>
            {work.map((project: any) => {
              return (
                <div>
                  <hr className={styles.hr} />
                  <ProjectCard project={project} />
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
