import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/common/navbar";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>jasonzubiate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.hero_content}>
            <h1 className={styles.h1}>Jason Zubiate</h1>
            <h2 className={styles.h2}>0 to 1 designer - of software, interfaces, and experiences</h2>
            <div className={styles.statuses}>
              <div className={styles.status}>
                <label className={styles.status_title}>Currenly</label>
                <label className={styles.status_body}>
                  UX Lead @ <span className={styles.bold}>Nutripair</span>
                </label>
              </div>
              <div className={styles.status}>
                <label className={styles.status_title}>Thinking About</label>
                <label className={styles.status_body}>
                  Latest design trends, AI potential, new techniques in dance
                  music production
                </label>
              </div>
              <div className={styles.status}>
                <label className={styles.status_title}>Previously</label>
                <label className={styles.status_body}>
                  B.S. Informatics: Human-Computer Interaction
                </label>
              </div>
            </div>
          </div>
          <div className={styles.hero_image}></div>
        </div>
      </main>
    </>
  );
}
